In [1]:
import tensorflow as tf

In [4]:
hello=tf.constant("Hello")
world=tf.constant("world")
sess=tf.InteractiveSession()
sess.run(hello+world)

C:\Users\rajat\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


b'Helloworld'

In [5]:
a=tf.constant("10")
b=tf.constant("20")
sess.run(a+b)

b'1020'

In [10]:
zero=tf.zeros((4,4))
one=tf.ones(4,4)
rand_n=tf.random_normal((3,3),mean=0,stddev=1.0)
rand_u=tf.random_uniform((3,3),minval=2,maxval=9)
op=[zero,one,rand_n,rand_u]
for out in op:
    print(sess.run(out))
    print("\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[1 1 1 1]


[[ 0.627891    1.3342263  -0.7239888 ]
 [ 1.4473854   0.3442892  -0.02286964]
 [ 1.5951838  -1.8067439   0.05769742]]


[[8.24811   6.8548307 6.277727 ]
 [3.5440023 4.5829873 7.0620584]
 [3.5126348 4.167851  6.545084 ]]




In [15]:
mat1=tf.constant([[2,3],[4,5]])
mat2=tf.constant([[3],[8]])
sess.run(tf.matmul(mat1,mat2))

array([[30],
       [52]])